from enum import StrEnum


class AnalyticsActivitiesColumns(StrEnum):
    ACCOUNT_NAME = "Account name"
    ACCOUNT_NAMES = "Account names"
    ACTIVITY_API_ID = "Activity API ID"
    ACTIVITY_ID = "Activity ID"
    ADDED_TAG = "Added tag"
    ADDED_TAG_API_ID = "Added tag API ID"
    ASSIGNEE = "Assignee"
    ATTRIBUTED_TO = "Attributed to"
    AUTHOR = "Author"
    AUTOREPLY = "Autoreply"
    BCC = "Bcc"
    BUSINESS_HOURS = "Business hours"
    CC = "Cc"
    COMMENT_API_ID = "Comment API ID"
    CONTACT_HANDLE = "Contact handle"
    CONTACT_NAME = "Contact name"
    CONVERSATION_API_ID = "Conversation API ID"
    CONVERSATION_ID = "Conversation ID"
    CUSTOM_FIELD = "Custom Field"
    DIRECTION = "Direction"
    EXTRACT = "Extract"
    FIRST_RESPONSE = "First response"
    FROM = "From"
    HANDLE_TIME = "Handle time"
    INBOX = "Inbox"
    INBOX_API_ID = "Inbox API ID"
    INBOX_API_IDS_AT_ACTIVITY_TIME = "Inbox API IDs at activity time"
    INBOX_AT_ACTIVITY_TIME = "Inbox at activity time"
    LAST_SEGMENT_ACTIVITY = "Last segment activity"
    MESSAGE_API_ID = "Message API ID"
    MESSAGE_DATE = "Message date"
    MESSAGE_ID = "Message ID"
    MESSAGE_ORIGINAL_ID = "Message original ID"
    NEW_CONVERSATION = "New Conversation"
    PREVIOUS_INBOX_IDS = "Previous inbox IDs"
    REACTION_TIME = "Reaction time"
    REMOVED_TAG = "Removed tag"
    REMOVED_TAG_API_ID = "Removed tag API ID"
    REPLIES_TO_RESOLUTION = "Replies to resolution"
    RESPONSE_TIME = "Response time"
    SEGMENT = "Segment"
    SEGMENT_CLOSED = "Segment closed"
    SEGMENT_CONTAINS_MESSAGES = "Segment contains messages"
    SEGMENT_CUMULATIVE_TEAMMATES = "Segment cumulative teammates"
    SEGMENT_END = "Segment end"
    SEGMENT_ID = "Segment ID"
    SEGMENT_START = "Segment start"
    SMART_QA_SCORE = "Smart QA score"
    SOURCE = "Source"
    STAGE_RESOLUTION_TIME = "Stage resolution time"
    STATUS = "Status"
    STATUS_AT_ACTIVITY_TIME = "Status at activity time"
    SUBJECT = "Subject"
    SURVEY_COMMENT = "Survey comment"
    SURVEY_RATING = "Survey rating"
    TAGS = "Tags"
    TAGS_AT_ACTIVITY_TIME = "Tags at activity time"
    TAG_API_IDS = "Tag API IDs"
    TAG_API_IDS_AT_ACTIVITY_TIME = "Tag API IDs at activity time"
    TAG_APPLICATION_DURATION = "Tag application duration"
    TICKET_IDS = "Ticket IDs"
    TICKET_REPLIES_TO_RESOLUTION = "Ticket replies to resolution"
    TICKET_RESOLUTION_TIME = "Ticket resolution time"
    TICKET_STATUS_CATEGORY = "Ticket status category"
    TICKET_STATUS_NAME = "Ticket status name"
    TIME_SPENT_IN_TICKET_STATUS = "Time spent in Ticket Status"
    TO = "To"
    TOTAL_REPLY_TIME = "Total reply time"
    TRANSITIONS_TO_TICKET_STATUS = "Transitions to Ticket Status"
    TYPE = "Type"
    UPDATED_CUSTOM_FIELD = "Updated Custom Field"

    def __str__(self) -> str:
        return str(self.value)
