from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import (
    define as _attrs_define,
    field as _attrs_field,
)

from ..client_types import UNSET, Unset
from ..models.message_response_draft_mode import MessageResponseDraftMode
from ..models.message_response_type import MessageResponseType

if TYPE_CHECKING:
    from ..models.attachment import Attachment
    from ..models.message_response_links import MessageResponseLinks
    from ..models.message_response_metadata import MessageResponseMetadata
    from ..models.recipient_response import RecipientResponse
    from ..models.signature_response import SignatureResponse
    from ..models.teammate_response import TeammateResponse


T = TypeVar("T", bound="MessageResponse")


@_attrs_define
class MessageResponse:
    r"""
    Attributes:
        field_links (MessageResponseLinks | Unset):
        id (str | Unset): Unique identifier of the message Example: msg_1q15qmtq.
        message_uid (str | Unset): Secondary unique identifier of a message. Generated by Front on message creation.
            Learn more at about the [message UID](https://dev.frontapp.com/reference/messages#creating-a-new-message).
            Example: 1eab543f84a0785f7b6b8967cck18f4d.
        type_ (MessageResponseType | Unset): Type of the message Example: email.
        is_inbound (bool | Unset): Whether or not the message has been received or sent
        draft_mode (MessageResponseDraftMode | Unset): If the message is a draft, describes the draft mode. Can be
            'private' (draft is visible to the author only) or 'shared' (draft is visible to all teammates with access to
            the conversation). Example: shared.
        error_type (str | Unset): Type of the error when the draft failed to be sent
        version (str | Unset): The current version of the message in Front Example:
            551ba368f3e7803cce51503ee3e58ef0-26028-1701804863304-945c.
        created_at (float | Unset): The timestamp when the message was sent or received Example: 1701292639.
        subject (str | Unset): Subject of the message Example: Jim's pranks are getting out of hand.
        blurb (str | Unset): Preview of the message body Example: It's high time we discuss the pranking culture in the
            office.
        author (TeammateResponse | Unset): A teammate is a user in Front.
        recipients (list[RecipientResponse] | Unset):
        body (str | Unset): Body of the message Example: <p>Hi there,</p><p>I wanted to let you know that I'm suggesting
            an update to <a href='https://dundermifflin.com/privacy/pranks'>Dunder Mifflin's Pranking Policy</a> to provide
            non-humorous employees greater control over their well-being in the office.</p>.
        text (str | Unset): Text version of the body for email messages Example: Hi there,\n\nI wanted to let you know
            that I'm suggesting an update to Dunder Mifflin's Pranking Policy (https://dundermifflin.com/privacy/pranks) to
            provide non-humorous employees greater control over their well-being in the office..
        attachments (list[Attachment] | Unset): List of files attached to the message
        signature (SignatureResponse | Unset):
        metadata (MessageResponseMetadata | Unset): Optional metadata about the message
    """

    field_links: MessageResponseLinks | Unset = UNSET
    id: str | Unset = UNSET
    message_uid: str | Unset = UNSET
    type_: MessageResponseType | Unset = UNSET
    is_inbound: bool | Unset = UNSET
    draft_mode: MessageResponseDraftMode | Unset = UNSET
    error_type: str | Unset = UNSET
    version: str | Unset = UNSET
    created_at: float | Unset = UNSET
    subject: str | Unset = UNSET
    blurb: str | Unset = UNSET
    author: TeammateResponse | Unset = UNSET
    recipients: list[RecipientResponse] | Unset = UNSET
    body: str | Unset = UNSET
    text: str | Unset = UNSET
    attachments: list[Attachment] | Unset = UNSET
    signature: SignatureResponse | Unset = UNSET
    metadata: MessageResponseMetadata | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        field_links: dict[str, Any] | Unset = UNSET
        if not isinstance(self.field_links, Unset):
            field_links = self.field_links.to_dict()

        id = self.id

        message_uid = self.message_uid

        type_: str | Unset = UNSET
        if not isinstance(self.type_, Unset):
            type_ = self.type_.value

        is_inbound = self.is_inbound

        draft_mode: str | Unset = UNSET
        if not isinstance(self.draft_mode, Unset):
            draft_mode = self.draft_mode.value

        error_type = self.error_type

        version = self.version

        created_at = self.created_at

        subject = self.subject

        blurb = self.blurb

        author: dict[str, Any] | Unset = UNSET
        if not isinstance(self.author, Unset):
            author = self.author.to_dict()

        recipients: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.recipients, Unset):
            recipients = []
            for recipients_item_data in self.recipients:
                recipients_item = recipients_item_data.to_dict()
                recipients.append(recipients_item)

        body = self.body

        text = self.text

        attachments: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.attachments, Unset):
            attachments = []
            for attachments_item_data in self.attachments:
                attachments_item = attachments_item_data.to_dict()
                attachments.append(attachments_item)

        signature: dict[str, Any] | Unset = UNSET
        if not isinstance(self.signature, Unset):
            signature = self.signature.to_dict()

        metadata: dict[str, Any] | Unset = UNSET
        if not isinstance(self.metadata, Unset):
            metadata = self.metadata.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if field_links is not UNSET:
            field_dict["_links"] = field_links
        if id is not UNSET:
            field_dict["id"] = id
        if message_uid is not UNSET:
            field_dict["message_uid"] = message_uid
        if type_ is not UNSET:
            field_dict["type"] = type_
        if is_inbound is not UNSET:
            field_dict["is_inbound"] = is_inbound
        if draft_mode is not UNSET:
            field_dict["draft_mode"] = draft_mode
        if error_type is not UNSET:
            field_dict["error_type"] = error_type
        if version is not UNSET:
            field_dict["version"] = version
        if created_at is not UNSET:
            field_dict["created_at"] = created_at
        if subject is not UNSET:
            field_dict["subject"] = subject
        if blurb is not UNSET:
            field_dict["blurb"] = blurb
        if author is not UNSET:
            field_dict["author"] = author
        if recipients is not UNSET:
            field_dict["recipients"] = recipients
        if body is not UNSET:
            field_dict["body"] = body
        if text is not UNSET:
            field_dict["text"] = text
        if attachments is not UNSET:
            field_dict["attachments"] = attachments
        if signature is not UNSET:
            field_dict["signature"] = signature
        if metadata is not UNSET:
            field_dict["metadata"] = metadata

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.attachment import Attachment
        from ..models.message_response_links import MessageResponseLinks
        from ..models.message_response_metadata import MessageResponseMetadata
        from ..models.recipient_response import RecipientResponse
        from ..models.signature_response import SignatureResponse
        from ..models.teammate_response import TeammateResponse

        d = dict(src_dict)
        _field_links = d.pop("_links", UNSET)
        field_links: MessageResponseLinks | Unset
        if isinstance(_field_links, Unset):
            field_links = UNSET
        else:
            field_links = MessageResponseLinks.from_dict(_field_links)

        id = d.pop("id", UNSET)

        message_uid = d.pop("message_uid", UNSET)

        _type_ = d.pop("type", UNSET)
        type_: MessageResponseType | Unset
        if isinstance(_type_, Unset):
            type_ = UNSET
        else:
            type_ = MessageResponseType(_type_)

        is_inbound = d.pop("is_inbound", UNSET)

        _draft_mode = d.pop("draft_mode", UNSET)
        draft_mode: MessageResponseDraftMode | Unset
        if isinstance(_draft_mode, Unset):
            draft_mode = UNSET
        else:
            draft_mode = MessageResponseDraftMode(_draft_mode)

        error_type = d.pop("error_type", UNSET)

        version = d.pop("version", UNSET)

        created_at = d.pop("created_at", UNSET)

        subject = d.pop("subject", UNSET)

        blurb = d.pop("blurb", UNSET)

        _author = d.pop("author", UNSET)
        author: TeammateResponse | Unset
        if isinstance(_author, Unset):
            author = UNSET
        else:
            author = TeammateResponse.from_dict(_author)

        _recipients = d.pop("recipients", UNSET)
        recipients: list[RecipientResponse] | Unset = UNSET
        if _recipients is not UNSET:
            recipients = []
            for recipients_item_data in _recipients:
                recipients_item = RecipientResponse.from_dict(recipients_item_data)

                recipients.append(recipients_item)

        body = d.pop("body", UNSET)

        text = d.pop("text", UNSET)

        _attachments = d.pop("attachments", UNSET)
        attachments: list[Attachment] | Unset = UNSET
        if _attachments is not UNSET:
            attachments = []
            for attachments_item_data in _attachments:
                attachments_item = Attachment.from_dict(attachments_item_data)

                attachments.append(attachments_item)

        _signature = d.pop("signature", UNSET)
        signature: SignatureResponse | Unset
        if isinstance(_signature, Unset):
            signature = UNSET
        else:
            signature = SignatureResponse.from_dict(_signature)

        _metadata = d.pop("metadata", UNSET)
        metadata: MessageResponseMetadata | Unset
        if isinstance(_metadata, Unset):
            metadata = UNSET
        else:
            metadata = MessageResponseMetadata.from_dict(_metadata)

        message_response = cls(
            field_links=field_links,
            id=id,
            message_uid=message_uid,
            type_=type_,
            is_inbound=is_inbound,
            draft_mode=draft_mode,
            error_type=error_type,
            version=version,
            created_at=created_at,
            subject=subject,
            blurb=blurb,
            author=author,
            recipients=recipients,
            body=body,
            text=text,
            attachments=attachments,
            signature=signature,
            metadata=metadata,
        )

        message_response.additional_properties = d
        return message_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
